#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Button;
                ref class TextBox;
                ref class PasswordBox;
            }
        }
    }
}

namespace DrivingSchool
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class ChangeTeacherPwd : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
    
        private: ::Windows::UI::Xaml::Controls::Button^ BackButton;
        private: ::Windows::UI::Xaml::Controls::TextBox^ IDBox;
        private: ::Windows::UI::Xaml::Controls::PasswordBox^ PwdBox;
        private: ::Windows::UI::Xaml::Controls::PasswordBox^ ConfirmPwdBox;
        private: ::Windows::UI::Xaml::Controls::Button^ ConfirmBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ ResetBtn;
    };
}

