#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBox;
                ref class Button;
                ref class TextBlock;
            }
        }
    }
}

namespace DrivingSchool
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MarkTeacher : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::TextBox^ ScoreBox;
        private: ::Windows::UI::Xaml::Controls::Button^ ConfirmBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ ResetBtn;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ IDBlock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TeacherBlock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ HistoryBlock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ AvgScoreBlock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ProgressNumberBlock;
    };
}

