#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Button;
                ref class PersonPicture;
                ref class TextBlock;
                ref class RatingControl;
            }
        }
    }
}

namespace DrivingSchool
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class ViewMark : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
    
        private: ::Windows::UI::Xaml::Controls::Button^ BackButton;
        private: ::Windows::UI::Xaml::Controls::PersonPicture^ PersonPic;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ NameBlock;
        private: ::Windows::UI::Xaml::Controls::RatingControl^ RatingCtrl;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ HistoryBlock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ IDBlock;
    };
}

